/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.satc.Eduarda;

import br.edu.satc.Eduarda.Objeto.Aluno;
import br.edu.satc.Eduarda.Objeto.TipoAvaliacao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {
   

    /**
     * Creates new form PricipalJava
     */
    public Principal() {
        initComponents();
        JComboBox combobox= new JComboBox();
        combobox.addItem("Avaliação");
        combobox.addItem("Trabalho");
        combobox.addItem("Seminário");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPAluno = new javax.swing.JPanel();
        jLTituloAluno = new javax.swing.JLabel();
        jLMatriculadoAluno = new javax.swing.JLabel();
        jTFnumeroDaMatricula = new javax.swing.JTextField();
        jLnomeA = new javax.swing.JLabel();
        jTFNomedoAluno = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jPdisciplina = new javax.swing.JPanel();
        jLnomedisciplina = new javax.swing.JLabel();
        jTFnNomedaDisciplina = new javax.swing.JTextField();
        jCBTipodeAvaliacao = new javax.swing.JComboBox<>();
        jPNotas = new javax.swing.JPanel();
        jLTituloNotas = new javax.swing.JLabel();
        jLNotaUm = new javax.swing.JLabel();
        jLNotaDois = new javax.swing.JLabel();
        jLNotaTres = new javax.swing.JLabel();
        jLNotaQuatro = new javax.swing.JLabel();
        jTFNota1doAluno = new javax.swing.JTextField();
        jTFNota2doAluno = new javax.swing.JTextField();
        jTFNota3doAluno = new javax.swing.JTextField();
        jTFNota4doAluno = new javax.swing.JTextField();
        jBcalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLTitulo.setText("Calculo de Média");

        jPAluno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTituloAluno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTituloAluno.setText("Aluno");

        jLMatriculadoAluno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLMatriculadoAluno.setText("Matrícula");

        jTFnumeroDaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnumeroDaMatriculaActionPerformed(evt);
            }
        });

        jLnomeA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnomeA.setText("Nome");

        jBCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLTituloAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLMatriculadoAluno))
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFnumeroDaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLnomeA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFNomedoAluno)))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBCadastrar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAluno)
                .addGap(31, 31, 31)
                .addComponent(jLMatriculadoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnumeroDaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLnomeA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFNomedoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrar)
                .addContainerGap())
        );

        jPdisciplina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLnomedisciplina.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnomedisciplina.setText("Nome da Disciplina");

        jCBTipodeAvaliacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avaliação", "Trabalho", "Seminário" }));
        jCBTipodeAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipodeAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPdisciplinaLayout = new javax.swing.GroupLayout(jPdisciplina);
        jPdisciplina.setLayout(jPdisciplinaLayout);
        jPdisciplinaLayout.setHorizontalGroup(
            jPdisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPdisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFnNomedaDisciplina)
                    .addGroup(jPdisciplinaLayout.createSequentialGroup()
                        .addGroup(jPdisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnomedisciplina)
                            .addComponent(jCBTipodeAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPdisciplinaLayout.setVerticalGroup(
            jPdisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdisciplinaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLnomedisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFnNomedaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jCBTipodeAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNotas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTituloNotas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTituloNotas.setText("Notas");

        jLNotaUm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLNotaUm.setText("N1");

        jLNotaDois.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLNotaDois.setText("N2");

        jLNotaTres.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLNotaTres.setText("N3");

        jLNotaQuatro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLNotaQuatro.setText("N4");

        jBcalcular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBcalcular.setText("Calcular");
        jBcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNotasLayout = new javax.swing.GroupLayout(jPNotas);
        jPNotas.setLayout(jPNotasLayout);
        jPNotasLayout.setHorizontalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLTituloNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLNotaQuatro)
                                .addComponent(jLNotaTres)
                                .addComponent(jLNotaDois, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLNotaUm))
                        .addGap(36, 36, 36)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcalcular)
                            .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFNota1doAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jTFNota3doAluno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFNota2doAluno)
                                .addComponent(jTFNota4doAluno, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNotasLayout.setVerticalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloNotas)
                .addGap(18, 18, 18)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNotaUm)
                    .addComponent(jTFNota1doAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNotaDois)
                    .addComponent(jTFNota2doAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNotaTres)
                    .addComponent(jTFNota3doAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNotaQuatro)
                    .addComponent(jTFNota4doAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jBcalcular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPdisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnumeroDaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnumeroDaMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnumeroDaMatriculaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        String nomeAluno;
       int matricula=0;
       
       nomeAluno = jTFNomedoAluno.getText();
        try {
            matricula = Integer.parseInt(jTFnumeroDaMatricula.getText());
            
        } catch (NumberFormatException nfe) {
        }
     
       
       
       Aluno j = new Aluno(nomeAluno,matricula);
       JOptionPane.showMessageDialog(this, j.toString());
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalcularActionPerformed
      TipoAvaliacao tipo = null;
        Aluno a = new Aluno (jTFNomedoAluno.getText(), Integer.parseInt(jTFnumeroDaMatricula.getText()));
        switch(jCBTipodeAvaliacao.getSelectedIndex()){
            case 1 :{
                tipo = TipoAvaliacao.getProva();
                break;
            } 
            
            case 2:{
                tipo = TipoAvaliacao.getSeminario();
                break;
            
           }
            
            case 3 :{
                tipo = TipoAvaliacao.getTrabalho();
                break;
            
            }
        
        }
        
       float n1,n2,n3,n4,media;
       String disciplina, nome;
       int matricula;
       
       
       
       matricula =Integer.parseInt(jTFnumeroDaMatricula.getText());
       n1 = Float.parseFloat(jTFNota1doAluno.getText());
       n2 = Float.parseFloat(jTFNota2doAluno.getText());
       n3 = Float.parseFloat(jTFNota3doAluno.getText());
       n4 = Float.parseFloat(jTFNota4doAluno.getText());
       disciplina =  jTFnNomedaDisciplina.getText();
       media  = (n1+n2+n3+n4)/4;
        JOptionPane.showMessageDialog(null, a.toString()+"media = " + media);
    }//GEN-LAST:event_jBcalcularActionPerformed

    private void jCBTipodeAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipodeAvaliacaoActionPerformed
    
        
        
    
    
  
         
    }//GEN-LAST:event_jCBTipodeAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBcalcular;
    private javax.swing.JComboBox<String> jCBTipodeAvaliacao;
    private javax.swing.JLabel jLMatriculadoAluno;
    private javax.swing.JLabel jLNotaDois;
    private javax.swing.JLabel jLNotaQuatro;
    private javax.swing.JLabel jLNotaTres;
    private javax.swing.JLabel jLNotaUm;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTituloAluno;
    private javax.swing.JLabel jLTituloNotas;
    private javax.swing.JLabel jLnomeA;
    private javax.swing.JLabel jLnomedisciplina;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNotas;
    private javax.swing.JPanel jPdisciplina;
    private javax.swing.JTextField jTFNomedoAluno;
    private javax.swing.JTextField jTFNota1doAluno;
    private javax.swing.JTextField jTFNota2doAluno;
    private javax.swing.JTextField jTFNota3doAluno;
    private javax.swing.JTextField jTFNota4doAluno;
    private javax.swing.JTextField jTFnNomedaDisciplina;
    private javax.swing.JTextField jTFnumeroDaMatricula;
    // End of variables declaration//GEN-END:variables
}
